spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: COMMERCE-SERVICE
          uri: lb://COMMERCE-SERVICE/
          predicates:
            - Path=/api/v1/commerce/**
          filters:
            - RewritePath=/api/v1/commerce/(?<path>.*), /api/v1/$\{path}
        - id: USER-SERVICE
          uri: lb://USER-SERVICE/
          predicates:
            - Path=/api/v1/users/**
          filters:
            - RewritePath=/api/v1/users/(?<path>.*), /api/v1/users/$\{path}
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE/
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RewritePath=/api/v1/auth/(?<path>.*), /api/v1/auth/$\{path}
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
logging:
  level:
    root: info
management:
  tracing:
    sampling:
      probability: 1.0