spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/{GIT_USER}/{CONFIG_REPOSITORY}
          username: { GIT_USER }
          password: { GIT_PASSWORD }
server:
  port: 8888